### ISSUE TITLE
Consider bundling "create an update PR" into the action

### ISSUE THREAD

**Issue by dbjorge** [dequelabs/update-axe-core#9]
Right now, in every case where our team actually uses this action, it's always with some boilerplate afterwards along these lines:

```yml
      - id: update
        uses: dequelabs/update-axe-core@v1
      - id: type
        run: |
          CommitType=""
          if [ "${{ steps.update.outputs.patch_version_updated }}" == "true" ]; then
            CommitType="fix"
          elif [ "${{ steps.update.outputs.minor_version_updated }}" == "true" ]; then
            CommitType="feat"
          elif [ "${{ steps.update.outputs.major_version_updated }}" == "true" ]; then
            CommitType="feat"
          fi
          echo "type=$CommitType" >>"$GITHUB_OUTPUT"
      - name: Open PR
        if: ${{ steps.type.outputs.type != '' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: '${{ steps.type.outputs.type }}: Update axe-core to v${{ steps.update.outputs.version }}'
          branch: auto-update-axe-core
          base: develop
          title: '${{ steps.type.outputs.type }}: Update axe-core to v${{ steps.update.outputs.version }}'
          body: |
            This patch updates version of [`axe-core`](https://npmjs.org/axe-core) to v${{ steps.update.outputs.version }}.

            This PR was opened by a robot :robot: :tada:.
```

We could remove a bunch of this boilerplate if we just enabled this action to file a PR itself in the standard format. It'd need to start accepting a `github_open_pr_token` param or similar anyway, so that could be made non-breaking by just skipping the PR step if the token param isn't specified.

(if we do this, probably do the "type" calculation in the existing script instead of using a separate step for it)
